--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Dezembro-21-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table IS_CACHE_HIT_STATS
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."IS_CACHE_HIT_STATS" 
   (	"DAY_ID" DATE, 
	"HOUR_ID" NUMBER, 
	"MINUTE_ID" FLOAT(126), 
	"CACHEINDEX" NUMBER(10,0), 
	"CACHESESSIONID" CHAR(32 BYTE), 
	"SERVERID" CHAR(32 BYTE), 
	"CACHEHITTIME" DATE, 
	"CACHEHITTYPE" NUMBER(10,0), 
	"CACHECREATORJOBID" NUMBER(10,0), 
	"CREATORSESSIONID" CHAR(32 BYTE), 
	"JOBID" NUMBER(10,0), 
	"STARTTIME" DATE, 
	"RECORDTIME" DATE, 
	"SERVERMACHINE" VARCHAR2(768 BYTE), 
	"PROJECTID" CHAR(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table IS_CUBE_REP_STATS
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."IS_CUBE_REP_STATS" 
   (	"DAY_ID" DATE, 
	"HOUR_ID" NUMBER, 
	"MINUTE_ID" FLOAT(126), 
	"SESSIONID" CHAR(32 BYTE), 
	"JOBID" NUMBER(10,0), 
	"PROJECTID" CHAR(32 BYTE), 
	"STARTTIME" DATE, 
	"FINISHTIME" DATE, 
	"CUBEREPORTGUID" CHAR(32 BYTE), 
	"CUBEINSTANCEID" CHAR(32 BYTE), 
	"CUBEACTIONID" NUMBER(*,0), 
	"REPORTGUID" CHAR(32 BYTE), 
	"CUBEKBSIZE" FLOAT(126), 
	"CUBEROWSIZE" FLOAT(126), 
	"RECORDTIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table IS_DOC_STEP_STATS
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."IS_DOC_STEP_STATS" 
   (	"DAY_ID" DATE, 
	"HOUR_ID" NUMBER, 
	"MINUTE_ID" FLOAT(126), 
	"JOBID" NUMBER(10,0), 
	"STEPSEQUENCE" NUMBER(10,0), 
	"SESSIONID" CHAR(32 BYTE), 
	"SERVERID" CHAR(32 BYTE), 
	"STEPTYPE" NUMBER(10,0), 
	"STARTTIME" DATE, 
	"FINISHTIME" DATE, 
	"QUEUETIME" FLOAT(126), 
	"CPUTIME" FLOAT(126), 
	"STEPDURATION" FLOAT(126), 
	"RECORDTIME" DATE, 
	"SERVERMACHINE" VARCHAR2(768 BYTE), 
	"PROJECTID" CHAR(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table IS_DOCUMENT_STATS
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."IS_DOCUMENT_STATS" 
   (	"DAY_ID" DATE, 
	"HOUR_ID" NUMBER, 
	"MINUTE_ID" FLOAT(126), 
	"JOBID" NUMBER(10,0), 
	"SESSIONID" CHAR(32 BYTE), 
	"SERVERID" CHAR(32 BYTE), 
	"SERVERNAME" VARCHAR2(768 BYTE), 
	"SERVERMACHINE" VARCHAR2(768 BYTE), 
	"PROJECTID" CHAR(32 BYTE), 
	"USERID" CHAR(32 BYTE), 
	"DOCUMENTID" CHAR(32 BYTE), 
	"REQUESTRECTIME" DATE, 
	"REQUESTQUEUETIME" FLOAT(126), 
	"STARTTIME" FLOAT(126), 
	"FINISHTIME" FLOAT(126), 
	"EXECSTATUS" NUMBER(10,0), 
	"EXECERRORCODE" NUMBER(10,0), 
	"REPORTCOUNT" NUMBER(10,0), 
	"CANCELINDICATOR" NUMBER(10,0), 
	"PROMPTINDICATOR" NUMBER(10,0), 
	"CACHEDINDICATOR" NUMBER(10,0), 
	"RECORDTIME" DATE, 
	"CPUTIME" FLOAT(126), 
	"STEPCOUNT" NUMBER(10,0), 
	"EXECDURATION" FLOAT(126), 
	"ERRORMESSAGE" VARCHAR2(4000 BYTE), 
	"EXECACTIONS" NUMBER(*,0), 
	"EXECFLAGS" NUMBER(*,0), 
	"PROMPTANSTIME" FLOAT(126), 
	"EXPORTINDIC" NUMBER(10,0), 
	"CACHECREATORJOBID" NUMBER(10,0), 
	"CACHECREATORSESSIONID" CHAR(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table IS_INBOX_ACT_STATS
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."IS_INBOX_ACT_STATS" 
   (	"DAY_ID" DATE, 
	"HOUR_ID" NUMBER, 
	"MINUTE_ID" FLOAT(126), 
	"SESSIONID" CHAR(32 BYTE), 
	"SERVERID" CHAR(32 BYTE), 
	"SERVERNAME" VARCHAR2(768 BYTE), 
	"SERVERMACHINE" VARCHAR2(768 BYTE), 
	"PROJECTID" CHAR(32 BYTE), 
	"INBOXACTION" NUMBER(10,0), 
	"USERID" CHAR(32 BYTE), 
	"USERNAME" VARCHAR2(768 BYTE), 
	"OWNERID" CHAR(32 BYTE), 
	"OWNERNAME" VARCHAR2(768 BYTE), 
	"MESSAGEID" CHAR(32 BYTE), 
	"MESSAGETITLE" VARCHAR2(768 BYTE), 
	"MESSAGEDISPNAME" VARCHAR2(768 BYTE), 
	"CREATIONTIME" DATE, 
	"STARTTIME" DATE, 
	"REPORTJOBID" NUMBER(10,0), 
	"DOCUMENTJOBID" NUMBER(10,0), 
	"SUBSCRIPTIONID" CHAR(32 BYTE), 
	"ACTIONCOMMENT" VARCHAR2(4000 BYTE), 
	"RECORDTIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table IS_MESSAGE_STATS
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" 
   (	"DAY_ID" DATE, 
	"HOUR_ID" NUMBER, 
	"MINUTE_ID" FLOAT(126), 
	"MESSAGEINDEX" NUMBER(10,0), 
	"SESSIONID" CHAR(32 BYTE), 
	"HISTORYLISTMESSAGEID" VARCHAR2(32 BYTE), 
	"SCHEDULEJOBID" NUMBER(10,0), 
	"FLAG1" NUMBER(10,0), 
	"FLAG2" NUMBER(10,0), 
	"DATATYPE" NUMBER(10,0), 
	"RECIPIENTCONTACTID" VARCHAR2(32 BYTE), 
	"DELIVERYTYPE" NUMBER(10,0), 
	"SUBSINSTID" VARCHAR2(32 BYTE), 
	"SCHEDULEID" VARCHAR2(32 BYTE), 
	"SUBINSTNAME" VARCHAR2(768 BYTE), 
	"DATAID" VARCHAR2(32 BYTE), 
	"CONTACTTYPE" NUMBER(10,0), 
	"RECIPIENTGROUPID" VARCHAR2(32 BYTE), 
	"RECIPIENTCONTACTNAME" VARCHAR2(768 BYTE), 
	"ISDEFAULTADDRESS" NUMBER(10,0), 
	"ADDRESSID" VARCHAR2(32 BYTE), 
	"DEVICEID" VARCHAR2(32 BYTE), 
	"ISNOTIFICATIONMESSAGE" NUMBER(10,0), 
	"NOTIFICATIONADDR" VARCHAR2(768 BYTE), 
	"SERVERID" VARCHAR2(32 BYTE), 
	"SERVERMACHINE" VARCHAR2(768 BYTE), 
	"PROJECTID" VARCHAR2(32 BYTE), 
	"EXECSTARTTIME" DATE, 
	"EXECFINISHTIME" DATE, 
	"RECORDTIME" DATE, 
	"DELIVERYSTATUS" NUMBER(10,0), 
	"PHYSICALADDRESS" VARCHAR2(768 BYTE), 
	"BATCHID" CHAR(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table IS_PERF_MON_STATS
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."IS_PERF_MON_STATS" 
   (	"DAY_ID" DATE, 
	"HOUR_ID" NUMBER, 
	"MINUTE_ID" FLOAT(126), 
	"SERVERMACHINE" VARCHAR2(100 BYTE), 
	"COUNTER_CAT" VARCHAR2(128 BYTE), 
	"COUNTER_INSTANCE" VARCHAR2(128 BYTE), 
	"COUNTER_NAME" VARCHAR2(128 BYTE), 
	"EVENT_TIME" DATE, 
	"COUNTER_VALUE" FLOAT(126), 
	"CTR_VAL_TYP" NUMBER(10,0), 
	"COUNTER_UNIT" VARCHAR2(768 BYTE), 
	"PROJECTID" CHAR(32 BYTE), 
	"RECORDTIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table IS_PR_ANS_STATS
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."IS_PR_ANS_STATS" 
   (	"DAY_ID" DATE, 
	"HOUR_ID" NUMBER, 
	"MINUTE_ID" FLOAT(126), 
	"JOBID" NUMBER(10,0), 
	"SESSIONID" CHAR(32 BYTE), 
	"PR_ORDER_ID" NUMBER(10,0), 
	"ANS_SEQ_ID" NUMBER(10,0) DEFAULT 1, 
	"PR_LOC_TYPE" NUMBER(10,0), 
	"PR_LOC_ID" CHAR(32 BYTE), 
	"PR_LOC_DESC" VARCHAR2(768 BYTE), 
	"PR_GUID" CHAR(32 BYTE), 
	"PR_NAME" VARCHAR2(768 BYTE), 
	"PR_TITLE" VARCHAR2(768 BYTE), 
	"PR_ANS_TYPE" NUMBER(10,0), 
	"PR_ANSWERS" VARCHAR2(4000 BYTE), 
	"PR_ANS_GUID" VARCHAR2(4000 BYTE), 
	"IS_REQUIRED" CHAR(1 BYTE), 
	"IS_DEFAULT" CHAR(1 BYTE), 
	"SERVERID" CHAR(32 BYTE), 
	"PROJECTID" CHAR(32 BYTE), 
	"SERVERMACHINE" VARCHAR2(768 BYTE), 
	"STARTTIME" DATE, 
	"RECORDTIME" DATE DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table IS_PROJ_SESS_STATS
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."IS_PROJ_SESS_STATS" 
   (	"DAY_ID" DATE, 
	"HOUR_ID" NUMBER, 
	"MINUTE_ID" FLOAT(126), 
	"SESSIONID" CHAR(32 BYTE), 
	"SERVERID" CHAR(32 BYTE), 
	"SERVERNAME" VARCHAR2(768 BYTE), 
	"SERVERMACHINE" VARCHAR2(768 BYTE), 
	"USERID" CHAR(32 BYTE), 
	"PROJECTID" CHAR(32 BYTE), 
	"CONNECTTIME" DATE, 
	"DISCONNECTTIME" DATE, 
	"EVENTNOTES" VARCHAR2(768 BYTE), 
	"RECORDTIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table IS_REP_COL_STATS
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."IS_REP_COL_STATS" 
   (	"DAY_ID" DATE, 
	"HOUR_ID" NUMBER, 
	"MINUTE_ID" FLOAT(126), 
	"JOBID" NUMBER(10,0), 
	"SESSIONID" CHAR(32 BYTE), 
	"SERVERID" CHAR(32 BYTE), 
	"TABLEID" CHAR(32 BYTE), 
	"COLUMNID" CHAR(32 BYTE), 
	"COLUMNNAME" VARCHAR2(768 BYTE), 
	"SQLCLAUSETYPEID" NUMBER(10,0), 
	"COUNTER" NUMBER(10,0), 
	"STARTTIME" DATE, 
	"RECORDTIME" DATE, 
	"SERVERMACHINE" VARCHAR2(768 BYTE), 
	"PROJECTID" CHAR(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table IS_REP_MANIP_STATS
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."IS_REP_MANIP_STATS" 
   (	"DAY_ID" DATE, 
	"HOUR_ID" NUMBER, 
	"MINUTE_ID" FLOAT(126), 
	"JOBID" NUMBER(10,0), 
	"SESSIONID" CHAR(32 BYTE), 
	"SERVERID" CHAR(32 BYTE), 
	"SERVERMACHINE" VARCHAR2(768 BYTE), 
	"PROJECTID" CHAR(32 BYTE), 
	"MANIPSEQUENCEID" NUMBER(10,0), 
	"MANIPTYPE" NUMBER(10,0), 
	"MANIPXML" VARCHAR2(768 BYTE), 
	"STARTTIME" DATE, 
	"FINISHTIME" DATE, 
	"MANIPDURATION" FLOAT(126), 
	"CHILDJOBID" NUMBER(10,0), 
	"USERID" CHAR(32 BYTE), 
	"REPORTID" CHAR(32 BYTE), 
	"RECORDTIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table IS_REPORT_STATS
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."IS_REPORT_STATS" 
   (	"DAY_ID" DATE, 
	"HOUR_ID" NUMBER, 
	"MINUTE_ID" FLOAT(126), 
	"JOBID" NUMBER(10,0), 
	"SESSIONID" CHAR(32 BYTE), 
	"SERVERID" CHAR(32 BYTE), 
	"SERVERNAME" VARCHAR2(768 BYTE), 
	"SERVERMACHINE" VARCHAR2(768 BYTE), 
	"PROJECTID" CHAR(32 BYTE), 
	"USERID" CHAR(32 BYTE), 
	"REPORTID" CHAR(32 BYTE), 
	"FILTERID" CHAR(32 BYTE), 
	"EMBEDDEDFILTER" NUMBER(10,0), 
	"TEMPLATEID" CHAR(32 BYTE), 
	"EMBEDDEDTEMPLATE" NUMBER(10,0), 
	"PARENTJOBID" NUMBER(10,0), 
	"DBINSTANCEID" CHAR(32 BYTE), 
	"DBUSERID" CHAR(32 BYTE), 
	"PARENTINDICATOR" NUMBER(10,0), 
	"REQUESTRECTIME" DATE, 
	"REQUESTQUEUETIME" FLOAT(126), 
	"EXECSTARTTIME" FLOAT(126), 
	"EXECFINISHTIME" FLOAT(126), 
	"SQLPASSES" NUMBER(10,0), 
	"JOBSTATUS" NUMBER(10,0), 
	"JOBERRORCODE" NUMBER(10,0), 
	"CANCELINDICATOR" NUMBER(10,0), 
	"ADHOCINDICATOR" NUMBER(10,0), 
	"PROMPTINDICATOR" NUMBER(10,0), 
	"DATAMARTINDICATOR" NUMBER(10,0), 
	"ELEMENTLOADINDIC" NUMBER(10,0), 
	"DRILLINDICATOR" NUMBER(10,0), 
	"SCHEDULEINDICATOR" NUMBER(10,0), 
	"CACHECREATEINDIC" NUMBER(10,0), 
	"PRIORITYNUMBER" NUMBER(10,0), 
	"JOBCOST" NUMBER(10,0), 
	"FINALRESULTSIZE" NUMBER(10,0), 
	"RECORDTIME" DATE, 
	"REPORTTYPE" NUMBER(10,0), 
	"ERRORMESSAGE" VARCHAR2(4000 BYTE), 
	"DRILLTEMPLATEUNIT" CHAR(32 BYTE), 
	"NEWOBJECT" CHAR(32 BYTE), 
	"DRILLTYPE" NUMBER(10,0), 
	"TOTALTABLEACCESS" NUMBER(10,0), 
	"SQLLENGTH" NUMBER(10,0), 
	"EXECDURATION" FLOAT(126), 
	"CPUTIME" FLOAT(126), 
	"STEPCOUNT" NUMBER(10,0), 
	"EXECACTIONS" NUMBER(10,0), 
	"EXECFLAGS" NUMBER(10,0), 
	"DBERRORINDIC" NUMBER(10,0), 
	"PROMPTANSTIME" FLOAT(126), 
	"CUBEINSTANCEID" CHAR(32 BYTE), 
	"CUBESIZE" NUMBER(10,0), 
	"SQLEXECINDIC" NUMBER(10,0), 
	"EXPORTINDIC" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table IS_REP_SEC_STATS
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."IS_REP_SEC_STATS" 
   (	"DAY_ID" DATE, 
	"HOUR_ID" NUMBER, 
	"MINUTE_ID" FLOAT(126), 
	"JOBID" NUMBER(10,0), 
	"SESSIONID" CHAR(32 BYTE), 
	"SECURITYFILTERSEQ" NUMBER(10,0), 
	"SERVERID" CHAR(32 BYTE), 
	"SECURITYFILTERID" CHAR(32 BYTE), 
	"RECORDTIME" DATE, 
	"SERVERMACHINE" VARCHAR2(768 BYTE), 
	"PROJECTID" CHAR(32 BYTE), 
	"STARTTIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table IS_REP_SQL_STATS
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."IS_REP_SQL_STATS" 
   (	"DAY_ID" DATE, 
	"HOUR_ID" NUMBER, 
	"MINUTE_ID" FLOAT(126), 
	"JOBID" NUMBER(10,0), 
	"SQLPASSSEQUENCE" NUMBER(10,0), 
	"SESSIONID" CHAR(32 BYTE), 
	"SERVERID" CHAR(32 BYTE), 
	"STARTTIME" DATE, 
	"FINISHTIME" DATE, 
	"EXECTIME" FLOAT(126), 
	"SQLSTATEMENT" VARCHAR2(4000 BYTE), 
	"SQLPASSTYPE" NUMBER(10,0), 
	"TOTALTABLEACCESSED" NUMBER(10,0), 
	"DBERRORMESSAGE" VARCHAR2(4000 BYTE), 
	"RECORDTIME" DATE, 
	"SERVERMACHINE" VARCHAR2(768 BYTE), 
	"PROJECTID" CHAR(32 BYTE), 
	"DBINSTANCEID" CHAR(32 BYTE), 
	"DBCONNECTIONID" CHAR(32 BYTE), 
	"DBLOGINID" CHAR(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table IS_REP_STEP_STATS
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."IS_REP_STEP_STATS" 
   (	"DAY_ID" DATE, 
	"HOUR_ID" NUMBER, 
	"MINUTE_ID" FLOAT(126), 
	"JOBID" NUMBER(10,0), 
	"STEPSEQUENCE" NUMBER(10,0), 
	"SESSIONID" CHAR(32 BYTE), 
	"SERVERID" CHAR(32 BYTE), 
	"STEPTYPE" NUMBER(10,0), 
	"STARTTIME" DATE, 
	"FINISHTIME" DATE, 
	"QUEUETIME" FLOAT(126), 
	"CPUTIME" FLOAT(126), 
	"STEPDURATION" FLOAT(126), 
	"RECORDTIME" DATE, 
	"SERVERMACHINE" VARCHAR2(768 BYTE), 
	"PROJECTID" CHAR(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table IS_SCHEDULE_STATS
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."IS_SCHEDULE_STATS" 
   (	"DAY_ID" DATE, 
	"HOUR_ID" NUMBER, 
	"MINUTE_ID" FLOAT(126), 
	"SCHEDULEID" NUMBER(10,0), 
	"SESSIONID" CHAR(32 BYTE), 
	"SERVERID" CHAR(32 BYTE), 
	"TRIGGERID" CHAR(32 BYTE), 
	"SCHEDULETYPE" NUMBER(10,0), 
	"HITCACHE" NUMBER(10,0), 
	"STARTTIME" DATE, 
	"RECORDTIME" DATE, 
	"SERVERMACHINE" VARCHAR2(768 BYTE), 
	"PROJECTID" CHAR(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table IS_SESSION_STATS
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."IS_SESSION_STATS" 
   (	"DAY_ID" DATE, 
	"HOUR_ID" NUMBER, 
	"MINUTE_ID" FLOAT(126), 
	"SESSIONID" CHAR(32 BYTE), 
	"SERVERID" CHAR(32 BYTE), 
	"SERVERNAME" VARCHAR2(768 BYTE), 
	"SERVERMACHINE" VARCHAR2(768 BYTE), 
	"PROJECTID" CHAR(32 BYTE), 
	"USERID" CHAR(32 BYTE), 
	"CLIENTMACHINE" VARCHAR2(768 BYTE), 
	"SESSIONEVENT" NUMBER(10,0), 
	"EVENTTIME" DATE, 
	"EVENTSOURCE" NUMBER(10,0), 
	"EVENTNOTES" VARCHAR2(768 BYTE), 
	"RECORDTIME" DATE, 
	"SERVERINSTNAME" VARCHAR2(768 BYTE), 
	"WEBMACHINE" VARCHAR2(768 BYTE), 
	"CONNECTTIME" DATE, 
	"DISCONNECTTIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table MSI_STATS_LOG
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."MSI_STATS_LOG" 
   (	"SESSIONID" CHAR(32 BYTE), 
	"PROJECTID" NUMBER(10,0), 
	"EVENTTIME" DATE, 
	"EVENT" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table MSI_STATS_PROP
--------------------------------------------------------

  CREATE TABLE "MSTR_STATISTICS"."MSI_STATS_PROP" 
   (	"PROP_NAME" VARCHAR2(768 BYTE), 
	"PROP_VAL" VARCHAR2(768 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
REM INSERTING into MSTR_STATISTICS.IS_CACHE_HIT_STATS
SET DEFINE OFF;
REM INSERTING into MSTR_STATISTICS.IS_CUBE_REP_STATS
SET DEFINE OFF;
REM INSERTING into MSTR_STATISTICS.IS_DOC_STEP_STATS
SET DEFINE OFF;
REM INSERTING into MSTR_STATISTICS.IS_DOCUMENT_STATS
SET DEFINE OFF;
REM INSERTING into MSTR_STATISTICS.IS_INBOX_ACT_STATS
SET DEFINE OFF;
REM INSERTING into MSTR_STATISTICS.IS_MESSAGE_STATS
SET DEFINE OFF;
REM INSERTING into MSTR_STATISTICS.IS_PERF_MON_STATS
SET DEFINE OFF;
REM INSERTING into MSTR_STATISTICS.IS_PR_ANS_STATS
SET DEFINE OFF;
REM INSERTING into MSTR_STATISTICS.IS_PROJ_SESS_STATS
SET DEFINE OFF;
REM INSERTING into MSTR_STATISTICS.IS_REP_COL_STATS
SET DEFINE OFF;
REM INSERTING into MSTR_STATISTICS.IS_REP_MANIP_STATS
SET DEFINE OFF;
REM INSERTING into MSTR_STATISTICS.IS_REPORT_STATS
SET DEFINE OFF;
REM INSERTING into MSTR_STATISTICS.IS_REP_SEC_STATS
SET DEFINE OFF;
REM INSERTING into MSTR_STATISTICS.IS_REP_SQL_STATS
SET DEFINE OFF;
REM INSERTING into MSTR_STATISTICS.IS_REP_STEP_STATS
SET DEFINE OFF;
REM INSERTING into MSTR_STATISTICS.IS_SCHEDULE_STATS
SET DEFINE OFF;
REM INSERTING into MSTR_STATISTICS.IS_SESSION_STATS
SET DEFINE OFF;
REM INSERTING into MSTR_STATISTICS.MSI_STATS_LOG
SET DEFINE OFF;
REM INSERTING into MSTR_STATISTICS.MSI_STATS_PROP
SET DEFINE OFF;
Insert into MSTR_STATISTICS.MSI_STATS_PROP (PROP_NAME,PROP_VAL) values ('VERSION','9.2');
Insert into MSTR_STATISTICS.MSI_STATS_PROP (PROP_NAME,PROP_VAL) values ('MAXSQLLENGTH','4000');
Insert into MSTR_STATISTICS.MSI_STATS_PROP (PROP_NAME,PROP_VAL) values ('MAXPRANSLENGTH','4000');
--------------------------------------------------------
--  DDL for Index IS_INB_ACT_STATS_IDX
--------------------------------------------------------

  CREATE INDEX "MSTR_STATISTICS"."IS_INB_ACT_STATS_IDX" ON "MSTR_STATISTICS"."IS_INBOX_ACT_STATS" ("OWNERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Index IS_REP_SEC_STATS_IDX
--------------------------------------------------------

  CREATE INDEX "MSTR_STATISTICS"."IS_REP_SEC_STATS_IDX" ON "MSTR_STATISTICS"."IS_REP_SEC_STATS" ("JOBID", "SESSIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Index SYS_C0035074
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSTR_STATISTICS"."SYS_C0035074" ON "MSTR_STATISTICS"."IS_REPORT_STATS" ("SESSIONID", "JOBID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Index SYS_C0035075
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSTR_STATISTICS"."SYS_C0035075" ON "MSTR_STATISTICS"."IS_REP_STEP_STATS" ("SESSIONID", "JOBID", "STEPSEQUENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Index SYS_C0035076
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSTR_STATISTICS"."SYS_C0035076" ON "MSTR_STATISTICS"."IS_REP_SQL_STATS" ("SESSIONID", "JOBID", "SQLPASSSEQUENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Index SYS_C0035077
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSTR_STATISTICS"."SYS_C0035077" ON "MSTR_STATISTICS"."IS_REP_COL_STATS" ("SESSIONID", "JOBID", "TABLEID", "COLUMNNAME", "SQLCLAUSETYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Index SYS_C0035078
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSTR_STATISTICS"."SYS_C0035078" ON "MSTR_STATISTICS"."IS_REP_MANIP_STATS" ("JOBID", "SESSIONID", "MANIPSEQUENCEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Index SYS_C0035079
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSTR_STATISTICS"."SYS_C0035079" ON "MSTR_STATISTICS"."IS_CACHE_HIT_STATS" ("CACHEINDEX", "CACHESESSIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Index SYS_C0035080
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSTR_STATISTICS"."SYS_C0035080" ON "MSTR_STATISTICS"."IS_SCHEDULE_STATS" ("SESSIONID", "SCHEDULEID", "SERVERID", "TRIGGERID", "HITCACHE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Index SYS_C0035081
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSTR_STATISTICS"."SYS_C0035081" ON "MSTR_STATISTICS"."IS_DOCUMENT_STATS" ("SESSIONID", "JOBID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Index SYS_C0035082
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSTR_STATISTICS"."SYS_C0035082" ON "MSTR_STATISTICS"."IS_DOC_STEP_STATS" ("SESSIONID", "JOBID", "STEPSEQUENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Index SYS_C0035083
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSTR_STATISTICS"."SYS_C0035083" ON "MSTR_STATISTICS"."IS_PR_ANS_STATS" ("JOBID", "SESSIONID", "PR_ORDER_ID", "ANS_SEQ_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Index SYS_C0035084
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSTR_STATISTICS"."SYS_C0035084" ON "MSTR_STATISTICS"."IS_MESSAGE_STATS" ("MESSAGEINDEX", "SESSIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  Constraints for Table IS_CACHE_HIT_STATS
--------------------------------------------------------

  ALTER TABLE "MSTR_STATISTICS"."IS_CACHE_HIT_STATS" ADD PRIMARY KEY ("CACHEINDEX", "CACHESESSIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D"  ENABLE;
  ALTER TABLE "MSTR_STATISTICS"."IS_CACHE_HIT_STATS" MODIFY ("STARTTIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_CACHE_HIT_STATS" MODIFY ("CACHESESSIONID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_CACHE_HIT_STATS" MODIFY ("CACHEINDEX" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_CACHE_HIT_STATS" MODIFY ("MINUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_CACHE_HIT_STATS" MODIFY ("HOUR_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_CACHE_HIT_STATS" MODIFY ("DAY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IS_CUBE_REP_STATS
--------------------------------------------------------

  ALTER TABLE "MSTR_STATISTICS"."IS_CUBE_REP_STATS" MODIFY ("CUBEACTIONID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_CUBE_REP_STATS" MODIFY ("FINISHTIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_CUBE_REP_STATS" MODIFY ("STARTTIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_CUBE_REP_STATS" MODIFY ("PROJECTID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_CUBE_REP_STATS" MODIFY ("MINUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_CUBE_REP_STATS" MODIFY ("HOUR_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_CUBE_REP_STATS" MODIFY ("DAY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IS_DOC_STEP_STATS
--------------------------------------------------------

  ALTER TABLE "MSTR_STATISTICS"."IS_DOC_STEP_STATS" ADD PRIMARY KEY ("SESSIONID", "JOBID", "STEPSEQUENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D"  ENABLE;
  ALTER TABLE "MSTR_STATISTICS"."IS_DOC_STEP_STATS" MODIFY ("STARTTIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_DOC_STEP_STATS" MODIFY ("SESSIONID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_DOC_STEP_STATS" MODIFY ("STEPSEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_DOC_STEP_STATS" MODIFY ("JOBID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_DOC_STEP_STATS" MODIFY ("MINUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_DOC_STEP_STATS" MODIFY ("HOUR_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_DOC_STEP_STATS" MODIFY ("DAY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IS_DOCUMENT_STATS
--------------------------------------------------------

  ALTER TABLE "MSTR_STATISTICS"."IS_DOCUMENT_STATS" ADD PRIMARY KEY ("SESSIONID", "JOBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D"  ENABLE;
  ALTER TABLE "MSTR_STATISTICS"."IS_DOCUMENT_STATS" MODIFY ("REQUESTRECTIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_DOCUMENT_STATS" MODIFY ("SESSIONID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_DOCUMENT_STATS" MODIFY ("JOBID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_DOCUMENT_STATS" MODIFY ("MINUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_DOCUMENT_STATS" MODIFY ("HOUR_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_DOCUMENT_STATS" MODIFY ("DAY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IS_INBOX_ACT_STATS
--------------------------------------------------------

  ALTER TABLE "MSTR_STATISTICS"."IS_INBOX_ACT_STATS" MODIFY ("STARTTIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_INBOX_ACT_STATS" MODIFY ("INBOXACTION" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_INBOX_ACT_STATS" MODIFY ("PROJECTID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_INBOX_ACT_STATS" MODIFY ("MINUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_INBOX_ACT_STATS" MODIFY ("HOUR_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_INBOX_ACT_STATS" MODIFY ("DAY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IS_MESSAGE_STATS
--------------------------------------------------------

  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" ADD PRIMARY KEY ("MESSAGEINDEX", "SESSIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D"  ENABLE;
  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" MODIFY ("EXECSTARTTIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" MODIFY ("PROJECTID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" MODIFY ("ISNOTIFICATIONMESSAGE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" MODIFY ("DEVICEID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" MODIFY ("ADDRESSID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" MODIFY ("ISDEFAULTADDRESS" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" MODIFY ("CONTACTTYPE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" MODIFY ("DELIVERYTYPE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" MODIFY ("RECIPIENTCONTACTID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" MODIFY ("FLAG2" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" MODIFY ("FLAG1" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" MODIFY ("SCHEDULEJOBID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" MODIFY ("HISTORYLISTMESSAGEID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" MODIFY ("SESSIONID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" MODIFY ("MESSAGEINDEX" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" MODIFY ("MINUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" MODIFY ("HOUR_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_MESSAGE_STATS" MODIFY ("DAY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IS_PERF_MON_STATS
--------------------------------------------------------

  ALTER TABLE "MSTR_STATISTICS"."IS_PERF_MON_STATS" MODIFY ("EVENT_TIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PERF_MON_STATS" MODIFY ("COUNTER_NAME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PERF_MON_STATS" MODIFY ("COUNTER_INSTANCE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PERF_MON_STATS" MODIFY ("COUNTER_CAT" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PERF_MON_STATS" MODIFY ("SERVERMACHINE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PERF_MON_STATS" MODIFY ("MINUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PERF_MON_STATS" MODIFY ("HOUR_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PERF_MON_STATS" MODIFY ("DAY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IS_PR_ANS_STATS
--------------------------------------------------------

  ALTER TABLE "MSTR_STATISTICS"."IS_PR_ANS_STATS" ADD PRIMARY KEY ("JOBID", "SESSIONID", "PR_ORDER_ID", "ANS_SEQ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D"  ENABLE;
  ALTER TABLE "MSTR_STATISTICS"."IS_PR_ANS_STATS" MODIFY ("STARTTIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PR_ANS_STATS" MODIFY ("PR_ANS_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PR_ANS_STATS" MODIFY ("PR_TITLE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PR_ANS_STATS" MODIFY ("PR_LOC_DESC" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PR_ANS_STATS" MODIFY ("PR_LOC_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PR_ANS_STATS" MODIFY ("ANS_SEQ_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PR_ANS_STATS" MODIFY ("PR_ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PR_ANS_STATS" MODIFY ("SESSIONID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PR_ANS_STATS" MODIFY ("JOBID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PR_ANS_STATS" MODIFY ("MINUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PR_ANS_STATS" MODIFY ("HOUR_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PR_ANS_STATS" MODIFY ("DAY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IS_PROJ_SESS_STATS
--------------------------------------------------------

  ALTER TABLE "MSTR_STATISTICS"."IS_PROJ_SESS_STATS" MODIFY ("CONNECTTIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PROJ_SESS_STATS" MODIFY ("SESSIONID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PROJ_SESS_STATS" MODIFY ("MINUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PROJ_SESS_STATS" MODIFY ("HOUR_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_PROJ_SESS_STATS" MODIFY ("DAY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IS_REP_COL_STATS
--------------------------------------------------------

  ALTER TABLE "MSTR_STATISTICS"."IS_REP_COL_STATS" ADD PRIMARY KEY ("SESSIONID", "JOBID", "TABLEID", "COLUMNNAME", "SQLCLAUSETYPEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D"  ENABLE;
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_COL_STATS" MODIFY ("STARTTIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_COL_STATS" MODIFY ("COUNTER" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_COL_STATS" MODIFY ("SQLCLAUSETYPEID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_COL_STATS" MODIFY ("COLUMNNAME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_COL_STATS" MODIFY ("COLUMNID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_COL_STATS" MODIFY ("TABLEID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_COL_STATS" MODIFY ("SERVERID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_COL_STATS" MODIFY ("SESSIONID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_COL_STATS" MODIFY ("JOBID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_COL_STATS" MODIFY ("MINUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_COL_STATS" MODIFY ("HOUR_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_COL_STATS" MODIFY ("DAY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IS_REP_MANIP_STATS
--------------------------------------------------------

  ALTER TABLE "MSTR_STATISTICS"."IS_REP_MANIP_STATS" ADD PRIMARY KEY ("JOBID", "SESSIONID", "MANIPSEQUENCEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D"  ENABLE;
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_MANIP_STATS" MODIFY ("STARTTIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_MANIP_STATS" MODIFY ("MANIPTYPE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_MANIP_STATS" MODIFY ("MANIPSEQUENCEID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_MANIP_STATS" MODIFY ("PROJECTID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_MANIP_STATS" MODIFY ("SERVERID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_MANIP_STATS" MODIFY ("SESSIONID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_MANIP_STATS" MODIFY ("JOBID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_MANIP_STATS" MODIFY ("MINUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_MANIP_STATS" MODIFY ("HOUR_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_MANIP_STATS" MODIFY ("DAY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IS_REPORT_STATS
--------------------------------------------------------

  ALTER TABLE "MSTR_STATISTICS"."IS_REPORT_STATS" ADD PRIMARY KEY ("SESSIONID", "JOBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D"  ENABLE;
  ALTER TABLE "MSTR_STATISTICS"."IS_REPORT_STATS" MODIFY ("REQUESTRECTIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REPORT_STATS" MODIFY ("SESSIONID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REPORT_STATS" MODIFY ("JOBID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REPORT_STATS" MODIFY ("MINUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REPORT_STATS" MODIFY ("HOUR_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REPORT_STATS" MODIFY ("DAY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IS_REP_SEC_STATS
--------------------------------------------------------

  ALTER TABLE "MSTR_STATISTICS"."IS_REP_SEC_STATS" MODIFY ("STARTTIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_SEC_STATS" MODIFY ("SECURITYFILTERID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_SEC_STATS" MODIFY ("SECURITYFILTERSEQ" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_SEC_STATS" MODIFY ("SESSIONID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_SEC_STATS" MODIFY ("JOBID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IS_REP_SQL_STATS
--------------------------------------------------------

  ALTER TABLE "MSTR_STATISTICS"."IS_REP_SQL_STATS" ADD PRIMARY KEY ("SESSIONID", "JOBID", "SQLPASSSEQUENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D"  ENABLE;
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_SQL_STATS" MODIFY ("STARTTIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_SQL_STATS" MODIFY ("SESSIONID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_SQL_STATS" MODIFY ("SQLPASSSEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_SQL_STATS" MODIFY ("JOBID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_SQL_STATS" MODIFY ("MINUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_SQL_STATS" MODIFY ("HOUR_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_SQL_STATS" MODIFY ("DAY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IS_REP_STEP_STATS
--------------------------------------------------------

  ALTER TABLE "MSTR_STATISTICS"."IS_REP_STEP_STATS" ADD PRIMARY KEY ("SESSIONID", "JOBID", "STEPSEQUENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D"  ENABLE;
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_STEP_STATS" MODIFY ("STARTTIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_STEP_STATS" MODIFY ("SESSIONID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_STEP_STATS" MODIFY ("STEPSEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_STEP_STATS" MODIFY ("JOBID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_STEP_STATS" MODIFY ("MINUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_STEP_STATS" MODIFY ("HOUR_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_REP_STEP_STATS" MODIFY ("DAY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IS_SCHEDULE_STATS
--------------------------------------------------------

  ALTER TABLE "MSTR_STATISTICS"."IS_SCHEDULE_STATS" ADD PRIMARY KEY ("SESSIONID", "SCHEDULEID", "SERVERID", "TRIGGERID", "HITCACHE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D"  ENABLE;
  ALTER TABLE "MSTR_STATISTICS"."IS_SCHEDULE_STATS" MODIFY ("STARTTIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_SCHEDULE_STATS" MODIFY ("HITCACHE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_SCHEDULE_STATS" MODIFY ("TRIGGERID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_SCHEDULE_STATS" MODIFY ("SERVERID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_SCHEDULE_STATS" MODIFY ("SESSIONID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_SCHEDULE_STATS" MODIFY ("SCHEDULEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IS_SESSION_STATS
--------------------------------------------------------

  ALTER TABLE "MSTR_STATISTICS"."IS_SESSION_STATS" MODIFY ("CONNECTTIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_SESSION_STATS" MODIFY ("EVENTTIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_SESSION_STATS" MODIFY ("SESSIONEVENT" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_SESSION_STATS" MODIFY ("SESSIONID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_SESSION_STATS" MODIFY ("MINUTE_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_SESSION_STATS" MODIFY ("HOUR_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."IS_SESSION_STATS" MODIFY ("DAY_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table MSI_STATS_PROP
--------------------------------------------------------

  ALTER TABLE "MSTR_STATISTICS"."MSI_STATS_PROP" MODIFY ("PROP_VAL" NOT NULL ENABLE);
  ALTER TABLE "MSTR_STATISTICS"."MSI_STATS_PROP" MODIFY ("PROP_NAME" NOT NULL ENABLE);



















