--------------------------------------------------------
--  Arquivo criado - Sexta-feira-Dezembro-21-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DSSCSCONTENT
--------------------------------------------------------

  CREATE TABLE "MSTR_HISTORY"."DSSCSCONTENT" 
   (	"CONTENT_ID" CHAR(32 BYTE), 
	"SUB_ID" NUMBER(10,0), 
	"SLICE_ID" NUMBER(10,0), 
	"VAL_SEQ" NUMBER(10,0), 
	"REF_COUNT" NUMBER(10,0), 
	"CONTENT_VALUE" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" 
 LOB ("CONTENT_VALUE") STORE AS BASICFILE (
  TABLESPACE "MAG_D" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table DSSCSMSGINFO
--------------------------------------------------------

  CREATE TABLE "MSTR_HISTORY"."DSSCSMSGINFO" 
   (	"MESSAGE_ID" CHAR(32 BYTE), 
	"SUBINST_ID" CHAR(32 BYTE), 
	"OBJECT_ID" CHAR(32 BYTE), 
	"FOLDER_ID" CHAR(32 BYTE), 
	"PROJECT_ID" CHAR(32 BYTE), 
	"OBJECT_NAME" NVARCHAR2(250), 
	"OBJECT_OWNER_NAME" NVARCHAR2(250), 
	"PROJECT_NAME" NVARCHAR2(250), 
	"OBJECT_DESC" NVARCHAR2(250), 
	"FOLDER_NAME" NVARCHAR2(250), 
	"START_TIME" DATE, 
	"FINISH_TIME" DATE, 
	"USER_ID" CHAR(32 BYTE), 
	"PARENT_ID" CHAR(32 BYTE), 
	"RESULT_ID" CHAR(32 BYTE), 
	"TRIGGER_ID" CHAR(32 BYTE), 
	"MESSAGE_STATUS" NUMBER(10,0), 
	"MESSAGE_TYPE" NUMBER(10,0), 
	"REQUEST_STATUS" NUMBER(10,0), 
	"REQUEST_TYPE" NUMBER(10,0), 
	"CLIENT_TYPE" NUMBER(10,0), 
	"CREATION_TIME" DATE, 
	"MODIFICATION_TIME" DATE, 
	"LOCALE" NUMBER(10,0), 
	"LAST_ERROR_CODE" NUMBER(10,0), 
	"EXECUTING_NODE" CHAR(32 BYTE), 
	"MESSAGE_TEXT" NVARCHAR2(1024), 
	"MESSAGE_DISPLAY_NAME" NVARCHAR2(250), 
	"OBJECT_VIEW_MEDIA" NUMBER(10,0), 
	"MESSAGE_OWNER_NAME" NVARCHAR2(250), 
	"OBJECT_ABBREVIATION" NVARCHAR2(250)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Table DSSCSRPTCACH
--------------------------------------------------------

  CREATE TABLE "MSTR_HISTORY"."DSSCSRPTCACH" 
   (	"CONTENT_ID" CHAR(32 BYTE), 
	"SUB_ID" NUMBER(10,0), 
	"SLICE_ID" NUMBER(10,0), 
	"VAL_SEQ" NUMBER(10,0), 
	"REF_COUNT" NUMBER(10,0), 
	"CONTENT_VALUE" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" 
 LOB ("CONTENT_VALUE") STORE AS BASICFILE (
  TABLESPACE "MAG_D" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table DSSCSSYSPROP
--------------------------------------------------------

  CREATE TABLE "MSTR_HISTORY"."DSSCSSYSPROP" 
   (	"PROP_NAME" VARCHAR2(250 BYTE), 
	"PROP_VAL" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
REM INSERTING into MSTR_HISTORY.DSSCSCONTENT
SET DEFINE OFF;
REM INSERTING into MSTR_HISTORY.DSSCSMSGINFO
SET DEFINE OFF;
REM INSERTING into MSTR_HISTORY.DSSCSRPTCACH
SET DEFINE OFF;
REM INSERTING into MSTR_HISTORY.DSSCSSYSPROP
SET DEFINE OFF;
Insert into MSTR_HISTORY.DSSCSSYSPROP (PROP_NAME,PROP_VAL) values ('VERSION','9.2');
Insert into MSTR_HISTORY.DSSCSSYSPROP (PROP_NAME,PROP_VAL) values ('ENCODING','UCS2');
Insert into MSTR_HISTORY.DSSCSSYSPROP (PROP_NAME,PROP_VAL) values ('CHARCHUNKSIZE','1024');
Insert into MSTR_HISTORY.DSSCSSYSPROP (PROP_NAME,PROP_VAL) values ('BINCHUNKSIZE','32000');
Insert into MSTR_HISTORY.DSSCSSYSPROP (PROP_NAME,PROP_VAL) values ('INLISTMAX','100');
--------------------------------------------------------
--  DDL for Index SYS_C0034928
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSTR_HISTORY"."SYS_C0034928" ON "MSTR_HISTORY"."DSSCSMSGINFO" ("MESSAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Index SYS_C0034929
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSTR_HISTORY"."SYS_C0034929" ON "MSTR_HISTORY"."DSSCSCONTENT" ("CONTENT_ID", "SUB_ID", "SLICE_ID", "VAL_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Index SYS_C0034930
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSTR_HISTORY"."SYS_C0034930" ON "MSTR_HISTORY"."DSSCSSYSPROP" ("PROP_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  DDL for Index SYS_C0034931
--------------------------------------------------------

  CREATE UNIQUE INDEX "MSTR_HISTORY"."SYS_C0034931" ON "MSTR_HISTORY"."DSSCSRPTCACH" ("CONTENT_ID", "SUB_ID", "SLICE_ID", "VAL_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D" ;
--------------------------------------------------------
--  Constraints for Table DSSCSCONTENT
--------------------------------------------------------

  ALTER TABLE "MSTR_HISTORY"."DSSCSCONTENT" ADD PRIMARY KEY ("CONTENT_ID", "SUB_ID", "SLICE_ID", "VAL_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D"  ENABLE;
  ALTER TABLE "MSTR_HISTORY"."DSSCSCONTENT" MODIFY ("CONTENT_VALUE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSCONTENT" MODIFY ("VAL_SEQ" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSCONTENT" MODIFY ("SLICE_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSCONTENT" MODIFY ("SUB_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSCONTENT" MODIFY ("CONTENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DSSCSMSGINFO
--------------------------------------------------------

  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" ADD PRIMARY KEY ("MESSAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D"  ENABLE;
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("MESSAGE_TEXT" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("LAST_ERROR_CODE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("LOCALE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("MODIFICATION_TIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("CREATION_TIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("CLIENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("REQUEST_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("REQUEST_STATUS" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("MESSAGE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("MESSAGE_STATUS" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("RESULT_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("FINISH_TIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("START_TIME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("FOLDER_NAME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("PROJECT_NAME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("OBJECT_NAME" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("FOLDER_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSMSGINFO" MODIFY ("MESSAGE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DSSCSRPTCACH
--------------------------------------------------------

  ALTER TABLE "MSTR_HISTORY"."DSSCSRPTCACH" ADD PRIMARY KEY ("CONTENT_ID", "SUB_ID", "SLICE_ID", "VAL_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D"  ENABLE;
  ALTER TABLE "MSTR_HISTORY"."DSSCSRPTCACH" MODIFY ("CONTENT_VALUE" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSRPTCACH" MODIFY ("VAL_SEQ" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSRPTCACH" MODIFY ("SLICE_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSRPTCACH" MODIFY ("SUB_ID" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSRPTCACH" MODIFY ("CONTENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DSSCSSYSPROP
--------------------------------------------------------

  ALTER TABLE "MSTR_HISTORY"."DSSCSSYSPROP" ADD PRIMARY KEY ("PROP_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAG_D"  ENABLE;
  ALTER TABLE "MSTR_HISTORY"."DSSCSSYSPROP" MODIFY ("PROP_VAL" NOT NULL ENABLE);
  ALTER TABLE "MSTR_HISTORY"."DSSCSSYSPROP" MODIFY ("PROP_NAME" NOT NULL ENABLE);




